"""Stable question step identifiers.

Every question row that participates in routing should carry ``step_id`` in JSON
(or ``question_key``). Legacy English-string lookup has been removed.
"""

from __future__ import annotations

# No legacy prompt→step map; routing uses ``step_id`` on question dicts only.
LEGACY_QUESTION_TO_STEP: dict[str, str] = {}

# --- Canonical step id strings (use in JSON ``step_id`` and ``elif step == ...``) ---
STEP_PASSKEY = "passkey"
STEP_EMAF_NAME = "emaf_name"
STEP_EMAF_PHONE = "emaf_phone"
STEP_EMAF_COMPANY = "emaf_company"
STEP_MEDICAL_PLAN_TYPE = "medical_plan_type"
STEP_UPLOAD_EMIRATES_DOC = "upload_emirates_doc"
STEP_UPLOAD_EID_BACK = "upload_eid_back"
STEP_UPLOAD_EID_FRONT = "upload_eid_front"
STEP_UPLOAD_DRIVING_LICENSE = "upload_driving_license"
STEP_UPLOAD_DRIVING_LICENSE_FRONT = "upload_driving_license_front"
STEP_UPLOAD_DRIVING_LICENSE_BACK = "upload_driving_license_back"
STEP_UPLOAD_TRADE_LICENSE = "upload_trade_license"
STEP_VAT_CERTIFICATE_CHOICE = "vat_certificate_choice"
STEP_UPLOAD_VAT_CERTIFICATE = "upload_vat_certificate"
STEP_UPLOAD_MULKIYA = "upload_mulkiya"
STEP_UPLOAD_MULKIYA_FRONT = "upload_mulkiya_front"
STEP_UPLOAD_MULKIYA_BACK = "upload_mulkiya_back"
STEP_GENDER_CONFIRM = "gender_confirm"
STEP_EMIRATE_CHOICE_MEDICAL = "emirate_choice_medical"
STEP_EMIRATE_CHOICE_CAR = "emirate_choice_car"
STEP_VEHICLE_REGISTRATION_TYPE = "vehicle_registration_type"
STEP_MOTOR_COVER_TYPE = "motor_cover_type"
STEP_SPONSOR_MOBILE = "sponsor_mobile"
STEP_SPONSOR_EMAIL = "sponsor_email"
STEP_CLIENT_NAME = "client_name"
STEP_CLIENT_MOBILE = "client_mobile"
STEP_MAIN_MENU = "main_menu"
STEP_MOTOR_MENU = "motor_menu"  # motor submenu (e.g. New Insurance vs Renewal)
STEP_IDS_MAIN_MENU = frozenset({STEP_MAIN_MENU, STEP_MOTOR_MENU})
STEP_MEDICAL_BRANCH = "medical_branch"
STEP_MEDICAL_VISA_EMIRATE = "medical_visa_emirate"
STEP_MARITAL_STATUS_MEMBER = "marital_status_member"
STEP_SPONSOR_MARITAL_STATUS = "sponsor_marital_status"
STEP_HEIGHT_CM = "height_cm"
STEP_WEIGHT_KG = "weight_kg"
STEP_INSURANCE_EXPIRY_YEAR = "insurance_expiry_year"
STEP_SPONSOR_COMPANY = "sponsor_company"
STEP_POLICY_RENEWAL_CHOICE = "policy_renewal_choice"
STEP_VALIDATE_NAME = "validate_name"
STEP_MEMBER_PURCHASE_NAME = "member_purchase_name"
STEP_SPONSOR_EMIRATES_ID = "sponsor_emirates_id"
STEP_VEHICLE_TEST_CERT = "vehicle_test_cert"
STEP_COMPREHENSIVE_COVER = "comprehensive_cover"
STEP_ADVISOR_CODE_ENTRY = "advisor_code_entry"
STEP_EXCEL_MEDICAL_UPLOAD = "excel_medical_upload"
STEP_ADVISOR_YES_NO = "advisor_yes_no"
STEP_SPONSOR_RELATIONSHIP = "sponsor_relationship"
STEP_MEDICAL_ADD_ANOTHER_MEMBER = "medical_add_another_member"
STEP_ADDITIONAL_MEMBER_RELATIONSHIP = "additional_member_relationship"
STEP_EMIRATE_CHOICE_ADDITIONAL_MEMBER = "emirate_choice_additional_member"
STEP_ADDITIONAL_MEMBER_RESIDENCY = "additional_member_residency"
STEP_SPONSOR_TYPE = "sponsor_type"
STEP_CURRENCY_CHOICE = "currency_choice"
STEP_MONTHLY_SALARY = "monthly_salary"
STEP_MEMBER_DOB = "member_dob"
STEP_MOTOR_REGISTRATION_CITY = "motor_registration_city"
STEP_MOTOR_CLAIM_POLICY_NUMBER = "motor_claim_policy_number"
STEP_CLAIM_TYPE_CHOICE = "claim_type_choice"
STEP_MOTOR_CLAIM_VEHICLE_REGISTRATION = "motor_claim_vehicle_registration"
STEP_MOTOR_CLAIM_DRIVING_LICENSE = "motor_claim_driving_license"
STEP_MOTOR_CLAIM_EMIRATES_ID = "motor_claim_emirates_id"
STEP_MOTOR_CLAIM_POLICE_VERIFICATION = "motor_claim_police_verification"
STEP_MOTOR_CLAIM_CONTACT_MOBILE = "motor_claim_contact_mobile"
STEP_MOTOR_CLAIM_REPAIR_WORKSHOP = "motor_claim_repair_workshop"
STEP_MOTOR_CLAIM_ROAD_RECOVERY = "motor_claim_road_recovery"
STEP_MOTOR_CLAIM_RECOVERY_LOCATION = "motor_claim_recovery_location"
STEP_MOTOR_CLAIM_REPURCHASE_OFFER = "motor_claim_repurchase_offer"
STEP_MEDICAL_CLAIM_ASSISTANCE_TYPE = "medical_claim_assistance_type"
STEP_MEDICAL_CLAIM_EMIRATES_ID_UPLOAD = "medical_claim_emirates_id_upload"
STEP_MEDICAL_CLAIM_INSURANCE_CARD_UPLOAD = "medical_claim_insurance_card_upload"
STEP_MEDICAL_CLAIM_CONTACT_MOBILE = "medical_claim_contact_mobile"
STEP_MEDICAL_CLAIM_REPURCHASE_OFFER = "medical_claim_repurchase_offer"

STEP_IDS_VALIDATE_NAME = frozenset({STEP_VALIDATE_NAME})
